config/routes.rb
Blogin15::Application.routes.draw do |map|
  resources :contact_forms

  devise_for :authors

  resources :authors

  resources :posts do
    resources :comments
  end

  root :to => "posts#index"

end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :registerable, :confirmable and :timeoutable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :age, :password, :password_confirmation

  has_many :posts, :dependent => :destroy
  validates :name, :age, :presence => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates_presence_of :author, :body
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name
  attribute :email
  attribute :author_id
  attribute :message

  validates :name, :email, :author_id, :message, :presence => true

  def headers
    { :to => Author.find(author_id).email }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :author

  validates_presence_of :title
  validates_presence_of :body
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_filter :authenticate_author!, :except => [:index, :show]

  # GET /authors
  # GET /authors.xml
  def index
    @authors = Author.all
    respond_with(@authors)
  end

  # GET /authors/1
  # GET /authors/1.xml
  def show
    @author = Author.find(params[:id])
    respond_with(@author)
  end

  # GET /authors/new
  # GET /authors/new.xml
  def new
    @author = Author.new
    respond_with(@author)
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.xml
  def create
    @author = Author.new(params[:author])
    @author.save
    respond_with(@author)
  end

  # PUT /authors/1
  # PUT /authors/1.xml
  def update
    @author = Author.find(params[:id])
    @author.update_attributes(params[:author])
    respond_with(@author)
  end

  # DELETE /authors/1
  # DELETE /authors/1.xml
  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    respond_with(@author)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_author!, :only => :destroy

  before_filter do
    @post = Post.find_by_id(params[:post_id])
  end

  def create
    @post.comments.create(params[:comment])
    redirect_to @post
  end

  def destroy
    comment = Comment.find_by_id(params[:id])
    comment.destroy
    redirect_to @post
  end

end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController
  # GET /contact_forms/new
  # GET /contact_forms/new.xml
  def new
    @contact_form = ContactForm.new
    respond_with(@contact_form)
  end

  # POST /contact_forms
  # POST /contact_forms.xml
  def create
    @contact_form = ContactForm.new(params[:contact_form])
    if @contact_form.deliver
      redirect_to root_path, :notice => "Thanks for your message"
    else
      render "new"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController  
  respond_to :atom, :only => :index
  before_filter :authenticate_author!, :except => [:index, :show]

  def index
    @posts = Post.order("created_at desc").includes(:author)
    respond_with @posts
  end

  def show
    @post = Post.find_by_id(params[:id])
    respond_with @post
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_author.posts.build(params[:post])
    @post.save
    respond_with(@post)
  end

  def edit
    @post = Post.find_by_id(params[:id])
  end

  def update
    @post = Post.find_by_id(params[:id])
    @post.update_attributes(params[:post])
    respond_with(@post)
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    @post.destroy
    respond_with(@post)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_forms_helper.rb
module ContactFormsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/_form.html.erb
<%= simple_form_for(@author) do |f| %>
  <%= f.error_messages %>

  <div class="inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :age %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.name %></td>
    <td><%= author.age %></td>
    <td><%= link_to 'Show', author %></td>
    <% if author_signed_in? %>
      <td><%= link_to 'Edit', edit_author_path(author) %></td>
      <td><%= link_to 'Destroy', author, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p>
  <b>Name:</b>
  <%= @author.name %>
</p>

<p>
  <b>Age:</b>
  <%= @author.age %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/contact_forms/new.html.erb
<h1>Send an author a message</h1>

<%= simple_form_for(@contact_form) do |f| %>
  <%= f.error_messages %>

  <div class="inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :author_id, :collection => Author.all %>
    <%= f.input :message, :as => :text %>
  </div>

  <div class="actions">
    <%= f.button :submit, "Send" %>
  </div>
<% end %>


<%= link_to 'Back', contact_forms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= controller_name.humanize %>: <%= action_name %></title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= auto_discovery_link_tag(:atom, posts_path(:atom)) %>
</head>
<body>
<div id="author_nav">
  <% if author_signed_in? %>
    Signed in as <%= current_author.name %>.
    <%= link_to "Edit", edit_author_path(current_author) %> |
    <%= link_to "Sign out", destroy_author_session_path %>
  <% else %>
    <%= link_to "Sign in", new_author_session_path %>
  <% end %>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |form| %>
  <%= form.error_messages %>

  <%= form.label :title, "Title" %>
  <%= form.text_field :title %>

  <%= form.label :body, "Body" %>
  <%= form.text_area :body %>

  <%= form.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit a post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<h1>My Blog!</h1>

<% @posts.each do |post| %>
<h2><%= link_to post.title, post %></h2> by <%= post.author.name %>
<div class="entry">
  <%= post.body %>
  <% if author_signed_in? %>
    <%= link_to "Edit", [:edit, post] %>
    <%= button_to "Delete", post,
        :confirm => "Are you sure?", :method => :delete %>
  <% end %>
  <hr/>
</div>
<% end %>
<%= link_to "New Post", new_post_path %>

app/views/posts/new.html.erb
<h1>Create a new post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1> by <%= @post.author.name %>
<div class="entry">
  <%= @post.body %>
</div>

<h2>Comments</h2>

<div class="comments">
  <% @post.comments.each do |comment| %>
    <h4>By: <%= comment.author %></h4>
    <div class="comment">
      <%= comment.body %>
    </div>
    <p>
      <%= button_to "Delete", [@post, comment], 
          :confirm => "Are you sure?", :method => :delete %>
    </p>
  <% end %>
</div>

<%= form_for [@post, Comment.new] do |form| %>
  <%= form.error_messages %>
  <%= form.label :author, "Name" %>
  <%= form.text_field :author %>

  <%= form.text_area :body %>

  <%= form.submit %>
<% end %>